Repository hexlet-project1/To-Do_List, pull requests merged in 2025-05, with the labels that each got.

#14 make frontend github tests
  .github/workflows/tests.yml
  frontend/.prettierignore
  frontend/__tests__/check_init.test.js
  frontend/eslint.config.js
  frontend/makefile
  frontend/package-lock.json
  frontend/package.json
Labels: 1-priority, to-review

#15 bugfix Update tests.yml
  .github/workflows/tests.yml
Labels: done, 1-priority

#17 fix makefile install backend and run
  backend/main.py
  backend/pyproject.toml
  backend/uv.lock
  frontend/index.html
  frontend/index.js
  frontend/render.js
  makefile
Labels: bug, 1-priority

#18 make frontend main app Closes #4
  frontend/css/index.css
  frontend/html/index.html
  frontend/js/app.js
  frontend/js/renderer.js
  frontend/js/todo-controller.js
  frontend/js/todo-model.js
  frontend/js/todo-view.js
Labels: 1-priority, to-review, feature

#19 hotfix Update app.js delete devTools
  frontend/js/app.js
Labels: bug, done, 1-priority

#23 make backend server responses
  backend/main.py
Labels: 1-priority, to-review, feature

#24 Update README.md
  README.md
Labels: 1-priority, to-review

#30 Fix/makefiles
  README.md
  backend/makefile
  frontend/makefile
  makefile
Labels: done

#32 Fix/makefiles
  .github/workflows/tests.yml
  .gitignore
  README.md
  backend/.python-version
  backend/main.py
  backend/makefile
  backend/pyproject.toml
  backend/uv.lock
  frontend/.prettierignore
  frontend/__tests__/check_init.test.js
  frontend/css/index.css
  frontend/eslint.config.js
  frontend/html/index.html
  frontend/js/app.js
  frontend/js/renderer.js
  frontend/js/todo-controller.js
  frontend/js/todo-model.js
  frontend/js/todo-view.js
  frontend/makefile
  frontend/package-lock.json
  frontend/package.json
  makefile
  run.bat
Labels: done, 1-priority

#33 refactoring/root_structure
  .gitignore
  run.bat
Labels: done, 1-priority

#34 Refactoring/frontend
  README.md
  backend/makefile
  frontend/.prettierignore
  frontend/eslint.config.js
  frontend/package-lock.json
  frontend/package.json
  makefile
Labels: done, 1-priority

#35 refactoring/backend
  backend/.python-version
  backend/makefile
  backend/pyproject.toml
  backend/uv.lock
Labels: done, 1-priority

#36 put makefile
  makefile
Labels: done, 1-priority

#37 github tests
  .github/workflows/tests.yml
  backend/tests/__pycache__/test_passing.cpython-310-pytest-8.3.5.pyc
  backend/tests/test_passing.py
  frontend/__tests__/check_init.test.js
Labels: done, 1-priority

#38 add frontend app
  frontend/css/index.css
  frontend/html/index.html
  frontend/js/app.js
  frontend/js/renderer.js
  frontend/js/todo-controller.js
  frontend/js/todo-model.js
  frontend/js/todo-view.js
Labels: done, 1-priority

#39 put backend responses, db conn, change frontend link to backend
  backend/main.py
  backend/py/__init__.py
  backend/py/app/__init__.py
  backend/py/app/__pycache__/todo_controller.cpython-310.pyc
  backend/py/app/__pycache__/todo_model.cpython-310.pyc
  backend/py/app/todo_controller.py
  backend/py/app/todo_model.py
  backend/py/db/__pycache__/db_config.cpython-310.pyc
  backend/py/db/__pycache__/db_init.cpython-310.pyc
  backend/py/db/__pycache__/db_utils.cpython-310.pyc
  backend/py/db/db_config.py
  backend/py/db/db_init.py
  backend/py/db/db_utils.py
  backend/pyproject.toml
  frontend/js/app.js
Labels: done, 1-priority

#40 make db model
  backend/py/db/todos_ER.png
Labels: done, 2-priority

#43 refactoring todos controller(make in class, delete ensure table,conn), model(db_ensure_table), main(all links), db* (func_names)
  backend/main.py
  backend/py/app/todo_controller.py
  backend/py/app/todo_model.py
  backend/py/db/db_init.py
  backend/py/db/db_utils.py
Labels: done, 1-priority

#46 fix prerelize structure x instrcution bugs
  README.md
  makefile
  run.bat
Labels: done, 1-priority

#48 fix dueDate type save db data to show in todos
  backend/py/app/todo_controller.py
  frontend/js/todo-controller.js
Labels: bug, done, 1-priority

#50 fix makefiles (tests and production/dev)
  backend/makefile
  backend/tests/__pycache__/test_passing.cpython-310-pytest-8.3.5.pyc
  frontend/makefile
  makefile
Labels: bug, done, 1-priority

#52 clear main.py, merge utillis, add pid in .gitignore
  .gitignore
  backend/main.py
  backend/py/app/todo_model.py
  backend/py/db/db_init.py
  backend/py/db/db_utils.py
  backend/py/utilities/ports.py
Labels: done, 1-priority

#55 add tests skip for branches tests/ and no fail if not exists tests p…
  backend/makefile
Labels: bug, 1-priority

#56 Revert "add tests skip for branches tests/ and no fail if not exists tests p…"
  backend/makefile
Labels: bug, 1-priority

#57 Revert "Revert "add tests skip for branches tests/ and no fail if not exists tests p…""
  backend/makefile
Labels: bug, 1-priority

#58 add all changes
  .github/workflows/tests.yml
  frontend/makefile
  frontend/package.json
Labels: bug, done, 1-priority

#59 brances tests to test
  .github/workflows/tests.yml
Labels: bug, done, 1-priority

#61 fix scripts : jest
  frontend/package.json
Labels: done, 1-priority

#67 release production v1.0.0
  README.md
  backend/.python-version
  backend/main.py
  backend/makefile
  backend/py/__init__.py
  backend/py/app/__init__.py
  backend/py/app/todo_controller.py
  backend/py/app/todo_model.py
  backend/py/db/db_config.py
  backend/py/db/db_utils.py
  backend/py/utilities/ports.py
  backend/pyproject.toml
  backend/uv.lock
  frontend/css/index.css
  frontend/html/index.html
  frontend/js/app.js
  frontend/js/renderer.js
  frontend/js/todo-controller.js
  frontend/js/todo-model.js
  frontend/js/todo-view.js
  frontend/makefile
  frontend/package-lock.json
  frontend/package.json
  makefile
Labels: done, 1-priority, production

#65 Merge pull request #11
  frontend/__tests__/check_init.test.js
  frontend/__tests__/todo-controller.test.js
  frontend/__tests__/todo-model.test.js
  frontend/__tests__/todo_view.test.js
  frontend/babel.config.json
  frontend/eslint.config.js
  frontend/jest.setup.js
  frontend/js/todo-controller.js
  frontend/package-lock.json
  frontend/package.json
Labels: done, 1-priority

#76 db add protection field types, fix db init
  backend/py/app/todo_controller.py
  backend/py/db/db_utils.py
  backend/py/db/todos_ER.png
  backend/uv.lock
Labels: done, 1-priority

#77 Update todo-model.test.js
  frontend/__tests__/todo-model.test.js
Labels: bug, done, 1-priority, hotfix

#80 release production v1.0.1
  backend/makefile
  backend/py/app/todo_controller.py
  backend/py/db/db_utils.py
  backend/uv.lock
  frontend/js/todo-controller.js
  frontend/js/todo-model.js
  frontend/makefile
  frontend/package-lock.json
  frontend/package.json
  makefile
Labels: done, 1-priority, production
